#!/bin/bash
# Source https://github.com/cadorn/bash.origin
. "$HOME/.bash.origin"
function init {
	eval BO_SELF_BASH_SOURCE="$BO_READ_SELF_BASH_SOURCE"
	BO_deriveSelfDir ___TMP___ "$BO_SELF_BASH_SOURCE"
	local __BO_DIR__="$___TMP___"


	pushd "$__BO_DIR__" > /dev/null
		export SMI_CACHE_DIRPATH="$__BO_DIR__/../.test.cache"

		rm -Rf "$SMI_CACHE_DIRPATH" > /dev/null || true
		rm -Rf "node_modules/" > /dev/null || true
		rm -Rf "sub/node_modules/" > /dev/null || true
		rm -Rf ".smi-for-npm" > /dev/null || true

		BO_callPlugin "$__BO_DIR__/../bash.origin.sourcemint" smi-for-npm install
	popd > /dev/null

}
init $@